### ISSUE TITLE
Transmission upgrades visualization refactor 

### ISSUE THREAD

**Issue by BainanXia** [Breakthrough-Energy/PostREISE#267]
As discussed with @danlivengood , we need to refactor [map_upgrades](https://github.com/Breakthrough-Energy/PostREISE/blob/develop/postreise/plot/plot_upgrades_map.py#L259) function in `plot_upgrades_map.py` to make it compatible for individual interconnections (now it is hard coded for USA scenarios only).

**Comment by danielolsen** [comment]
What's hardcoded right now that requires USA scenarios only is the list of DC lines which we know are actually B2Bs. We could create a dictionary, with keys as `(grid_model, interconnect)`, and values are the set of DC line indices that we know are actually B2Bs for each. Then, instead of hardcoding to USA, we can take any interconnect, and look up the appropriate B2Bs from there.

**Comment by rouille** [comment]
> What's hardcoded right now that requires USA scenarios only is the list of DC lines which we know are actually B2Bs. We could create a dictionary, with keys as `(grid_model, interconnect)`, and values are the set of DC line indices that we know are actually B2Bs for each. Then, instead of hardcoding to USA, we can take any interconnect, and look up the appropriate B2Bs from there.

I think this is what you did in `postreise.plot.plot_powerflow_snapshot` @danielolsen, is that correct?

**Comment by danielolsen** [comment]
@rouille in `postreise.plot.plot_powerflow_snapshot`, we let the user specify which DC lines are actually B2Bs, and if so, then at which end of the pseudo-AC-line to show the B2B symbol. We could enable the same thing here pretty simply.

My brainstorming about the dictionary was: the set of DC lines in our `usa_tamu` grid that we know are actually B2Bs is fixed, so it would be nice if the user didn't have the think about it, and it would be looked up automatically, perhaps from a dict in PostREISE somewhere or perhaps as part of `ModelImmutables`.

**Comment by BainanXia** [comment]
I was thinking of having DC line type defined in the data frame so that in the future the users could specify the type of DC lines that they would like to add/scale, etc. However, I realize the B2B dclines in our current network are not physically B2B (they don't have `from_bus_id` == `to_bus_id`) which makes it confused.

**Comment by danielolsen** [comment]
We could get around this for future scenarios if we modified the `usa_tamu` data to add the pseudo AC branches to the Grid, and changed the to/from buses of the DC lines to be at the same lat/lon. Then we could automatically determine whether a DC line is a B2B or not by its length. That doesn't help us for all previously-run scenarios though.

**Comment by rouille** [comment]
> @rouille in `postreise.plot.plot_powerflow_snapshot`, we let the user specify which DC lines are actually B2Bs, and if so, then at which end of the pseudo-AC-line to show the B2B symbol. We could enable the same thing here pretty simply.
> 
> 
> 
> My brainstorming about the dictionary was: the set of DC lines in our `usa_tamu` grid that we know are actually B2Bs is fixed, so it would be nice if the user didn't have the think about it, and it would be looked up automatically, perhaps from a dict in PostREISE somewhere or perhaps as part of `ModelImmutables`.

I like the idea to have it accessible through a ModelImmutables instance since it is inherent to the grid model. Perhaps, we can create a transmission module in powersimdata/network/usa_tamu/constants that will enclose this information and other ones related to transmission (colors, etc.)

**Comment by danielolsen** [comment]
I'm getting started on changes in my `daniel/plot_upgrades_map_flexibility` branch. So far, it can now take any two scenarios as long as they have matching grid models and interconnects, and it relies on the user passing the indices of the DC lines that are actually B2Bs (and we still assume that the B2Bs are at the 'from' end).
