### ISSUE TITLE
Matplotlib Deprecation Warning

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/PostREISE#277]
I encountered this warning:
```
The is_first_col function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. 
Use ax.get_subplotspec().is_first_col() instead
```
when running `plot_pie_generation_vs_capacity` and `plot_bar_generation_vs_capacity`. We don't use the `is_firt_col` function directly so it might be fixed by itself wit a new version of `pandas`

**Comment by merrielle** [comment]
pandas has updated and fixed the issue
