### ISSUE TITLE
Python 3.9 is not supported by pyproj 2.6.1.post1

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PostREISE#279]
pyproj 2.6.1.post1 documentation: https://pypi.org/project/pyproj/2.6.1.post1/

When upgrading from 1.x to 2.x, there were some significant changes, such that code that had previously run quickly was taking hours (see https://github.com/Breakthrough-Energy/PostREISE/pull/154). Hopefully, we will not run into such challenges going from 2.x to 3.x.

**Comment by merrielle** [comment]
Pyproj has been updated, bug resolved
