### ISSUE TITLE
Refactor plot_renewable_capacity_map

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/PostREISE#281]
Produce a map where all renewable generators are color coded by fuel type. Different shapes will be used for base grid and added ones (if there are in the input scenario). The size of the markers would indicate nameplate capacity.

**Comment by danielolsen** [comment]
I need to do something similar for analyzing some scenarios with new nuclear capacity, so I plan to roll that effort into this. I will allow the user to specify which type(s) of generators they want plotted, and which shapes to use for existing (scaled up) and new (added) generators.

**Comment by rouille** [comment]
Sounds good. In this module, there are a lot of lines of code that aim at building a customized legend. I would try to use the builtin legend.
